version: '3.8'

services:
  # MQTT Broker (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # Websocket (optional)
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: iot_user
      POSTGRES_PASSWORD: iot_password
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  # Grafana
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - postgres
    networks:
      - iot-network

  # Sensor Simulator (Python)
  sensor-simulator:
    build: ./sensor-simulator
    container_name: sensor-simulator
    depends_on:
      - mosquitto
      - postgres
    networks:
      - iot-network

volumes:
  postgres-data:

networks:
  iot-network:
    driver: bridge
